// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfyultpsfekadqplyhit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeXVsdHBzZmVrYWRxcGx5aGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MjMxNDksImV4cCI6MjA5NzE5OTE0OX0.gljT2-lPJgWpxc-hL5ts-dN4i7Y4FbZKPbg7XMHdmvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});